                                                                        'CALENDERS IN PQL'


Weekday Calendar :

CALC_THROUGHPUT(CASE_START TO CASE_END, REMAP_TIMESTAMPS("ACTIVITIES"."TIMESTAMP", HOURS))

CALC_THROUGHPUT(
    CASE_START TO CASE_END,
    REMAP_TIMESTAMPS(
         "ACTIVITIES"."TIMESTAMP",
        HOURS,
        WEEKDAY_CALENDAR(
            MONDAY TUESDAY WEDNESDAY THURSDAY FRIDAY
        )
    )
)

CALC_THROUGHPUT(
    CASE_START TO CASE_END,
    REMAP_TIMESTAMPS(
        "ACTIVITIES" ."TIMESTAMP",
        HOURS,
        WEEKDAY_CALENDAR(
            MONDAY 08:00-16:00
            TUESDAY 13:00-14:00
            WEDNESDAY 09:00-10:00
            THURSDAY 11:00-12:00
            FRIDAY 15:00-18:00
        )
    )
)


Workday Calendar :

CALC_THROUGHPUT(
  CASE_START TO CASE_END,
  REMAP_TIMESTAMPS(
    "ACTIVITIES"."TIMESTAMP",
    DAYS,
    WORKDAY_CALENDAR(
      "TFACS",
      'DE'
    )
  )
)



Factory Calendar  :

CALC_THROUGHPUT(
  CASE_START TO CASE_END,
  REMAP_TIMESTAMPS(
    "ACTIVITIES"."TIMESTAMP",
    HOURS,
    FACTORY_CALENDAR(
      "FACTORY_TABLE"."Start",
      "FACTORY_TABLE"."End"
    )
  )
)




Intersect :

CALC_THROUGHPUT(
  CASE_START TO CASE_END,
  REMAP_TIMESTAMPS(
    "ACTIVITIES"."TIMESTAMP",
    HOURS,
    INTERSECT(
      WORKDAY_CALENDAR("TFACS", 'DE'),
      WEEKDAY_CALENDAR(
        MONDAY 09:00 - 17:00
        TUESDAY 09:00 - 17:00,
        THURSDAY 09:00 - 17:00,
        FRIDAY 09:00 - 17:00
      )
    )
  )
)


Multiple parallel calendars :

FACTORY_CALENDAR("FACTORY_TABLE")

Workday:
REMAP_TIMESTAMPS("ACTIVITIES"."TIMESTAMP", DAYS, WORKDAY_CALENDAR("TFACS", 'IT'))
Factory:
REMAP_TIMESTAMPS("ACTIVITIES". "TIMESTAMP", MINUTES, FACTORY_CALENDAR("FACTORY_TABLE", 'IT'))

REMAP_TIMESTAMPS("ACTIVITIES"."TIMESTAMP" , DAYS, WORKDAY_CALENDAR("TFACS", "CASES"."COUNTRY"))

