(CASE WHEN STDEV(
  TARGET ( REMAP_TIMESTAMPS ( TIMESTAMP_COLUMN ( ) , seconds ) ) * 1.0
  -
SOURCE ( REMAP_TIMESTAMPS ( TIMESTAMP_COLUMN ( ) , seconds ) ) * 1.0 ) =0 THEN NULL ELSE CASE WHEN COUNT_TABLE(CASE_TABLE()) / GLOBAL(COUNT_TABLE(CASE_TABLE())) > 0.1 THEN STDEV(
  TARGET ( REMAP_TIMESTAMPS ( TIMESTAMP_COLUMN ( ) , seconds ) ) * 1.0
  -
SOURCE ( REMAP_TIMESTAMPS ( TIMESTAMP_COLUMN ( ) , seconds ) ) * 1.0 ) / 86400 ELSE NULL END END)* count_table(case_table())
