SUM(
  CASE
    WHEN PU_COUNT_DISTINCT("BSEG","_CEL_AP_ACTIVITIES"."USER_TYPE","_CEL_AP_ACTIVITIES"."USER_TYPE"='A')=0 
        AND PU_MAX("BSEG","_CEL_AP_ACTIVITIES"."USER_TYPE") IN ('B','C','S') 
    THEN 1.0
    ELSE 0.0
  END
)
