YEAR("_APX_WDCRP_ACTIVITIES"."EVENTTIME")

YEAR("_APX_WDCRP_ACTIVITIES"."EVENTTIME") || '-' || MONTH("_APX_WDCRP_ACTIVITIES"."EVENTTIME")

CONCAT(
  YEAR(ROUND_YEAR("_APX_WDCRP_ACTIVITIES"."EVENTTIME")),
  '-',
  CASE
    WHEN MONTH("_APX_WDCRP_ACTIVITIES"."EVENTTIME") BETWEEN 1 AND 3 THEN 'Q1'
    WHEN MONTH("_APX_WDCRP_ACTIVITIES"."EVENTTIME") BETWEEN 4 AND 6 THEN 'Q2'
    WHEN MONTH("_APX_WDCRP_ACTIVITIES"."EVENTTIME") BETWEEN 7 AND 9 THEN 'Q3'
    WHEN MONTH("_APX_WDCRP_ACTIVITIES"."EVENTTIME") BETWEEN 10 AND 12 THEN 'Q4'
  END
)

YEAR("_APX_WDCRP_ACTIVITIES"."EVENTTIME") || '-'|| CALENDAR_WEEK ( "_APX_WDCRP_ACTIVITIES"."EVENTTIME" )
